### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by 5H00T4**
Some small cleanup

### CODE REVIEW

**Comment by m4xw** [comment]
Thanks, but this will conflict with some already done internal changes.
I will backport the README changes and close the PR when pushed. 👍

**Comment by p-sam** [comment]
readme changes were pushed as of https://github.com/retronx-team/sys-clk/commit/b85054f79fabaee01e60cb7061267fb009a38c6b

**Comment by p-sam** [comment]
@5H00T4 is this still up to date? Branch has conflicts with the current README

**Comment by 5H00T4** [comment]
> @5H00T4 is this still up to date? Branch has conflicts with the current README

I resolved the conflicts, looked ok to me.
Was just a few updates and clarifications to the readme anyway.

**Pull request closed without merging**
